import { RootStyleRegistry } from '@/configs/AntdRegistry';
import { Inter } from 'next/font/google';
import React from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: any) => (
  <html lang="en">
    <body className={inter.className}>
      <RootStyleRegistry>{children}</RootStyleRegistry>
    </body>
  </html>
);

export default RootLayout;
