import ContentComponent from '@/components/layout/Content';
import FooterComponent from '@/components/layout/Footer';
import HeaderAdminComponent from '@/components/layout/HeaderAdmin';
import AdminSideBarComponent from '@/components/layout/SideBar';
import { Layout } from 'antd';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ProviderComponent from '@/configs/provider';
import { RootStyleRegistry } from '@/configs/AntdRegistry';

const inter = Inter({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderComponent>
          <RootStyleRegistry>
            <Layout>
              <HeaderAdminComponent />
              <Layout hasSider>
                <AdminSideBarComponent />

                <ContentComponent>{children}</ContentComponent>
              </Layout>
              <FooterComponent />
            </Layout>
          </RootStyleRegistry>
        </ProviderComponent>
      </body>
    </html>
  );
}
