import ContentComponent from '@/components/layout/Content';
import FooterComponent from '@/components/layout/Footer';
import HeaderClientComponent from '@/components/layout/HeaderClient';
import ProviderComponent from '@/configs/provider';
import { Layout } from 'antd';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({
  subsets: ['latin'],
});

export const metadata = {
  title: 'Shop online',
  description: 'Generated by Auth app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderComponent>
          <Layout>
            <HeaderClientComponent />
            <ContentComponent>{children}</ContentComponent>
            <FooterComponent />
          </Layout>
        </ProviderComponent>
      </body>
    </html>
  );
}
